services:

  app:
    build: .
    container_name: laravel_app

    ports:
      - "8000:80"

    volumes:
      - .:/var/www/html

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0

    container_name: mysql_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_webskripsi

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    container_name: phpmyadmin

    ports:
      - "8080:80"

    environment:
      PMA_HOST: mysql

    depends_on:
      - mysql

volumes:
  mysql_data: